---
- name: Update apt cache
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure MySQL client is present using yum
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
  - mysql-client
  when: ansible_os_family == 'RedHat' and {{ mysql["client"]["install"] }}

- name: Ensure MySQL client present using apt
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
  - mysql-client
  when: ansible_os_family == 'Debian' and {{ mysql["client"]["install"] }}

- debug: msg="MySQL server installation not enabled"
  when: not mysql["server"]["install"]

- include: server.yml
  when: mysql["server"]["install"]
