---
- name: Ensure MySQL client is present using apt
  become: yes
  apt:
    name: "{{ mysql.packages.client }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure MySQL server is present using apt
  become: yes
  apt:
    name: "{{ mysql.packages.server }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  when: mysql.install_server

- name: Ensure Python MySQL lib is present using apt
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ mysql.packages.python }}"
  when: mysql.install_server
