---
- name: Update MySQL Configuration
  sudo: yes
  template:
    src: "etc/mysql/conf.d/my.cnf.j2"
    dest: "{{ mysql['conf_dir'] }}/my.cnf"
    mode: 0644
  notify:
    - restart mysql

# TODO: Use a process manager, see: http://blog.crocodoc.com/post/48703468992/process-managers-the-good-the-bad-and-the-ugly

- name: Create DB users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: "{{ item.state | default('present') }}"
    host: "{{ item.host | default('localhost') }}"
    check_implicit_admin: yes
  with_items: mysql["users"]
  when: mysql["users"] is defined
  no_log: True

- name: Make sure DBs are present
  mysql_db:
    state: present
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: mysql["databases"]
  when: mysql["databases"] is defined
