---
- name: start mysql
  become: yes
  service: 
    name: "{{ mysql['service'] }}"
    state: started
    enabled: yes
    
- name: restart mysql
  become: yes
  service: 
    name: "{{ mysql['service'] }}"
    state: restarted
    enabled: yes    
